name: Build Deploy App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure CR
      uses: docker/login-action@v3
      with: 
        registry: ${{ vars.ACR_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: app
        tags: ${{ vars.ACR_REGISTRY }}.azurecr.io/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
    
    - name: Deploy the app
      run: |
        helm upgrade --install my-app app/2bcloud/ -n myapp